plugins:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

# https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecanyinstance
RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Exclude:
    - spec/controllers/api/v1/notes_controller_spec.rb
    - spec/controllers/boards_controller_spec.rb

Lint/EmptyBlock:
  Exclude:
    - spec/factories/board_factory.rb

AllCops:
  NewCops: enable
  Exclude:
    - .gitignore
    - .pryrc
    - ruby-advisory-db/**/*
    - docker-compose.yml
    - tmp
    - doc
    - db/**/*
    - config.ru
    - bin/**/*
    - Rakefile
    - config/**/*
    - vendor/**/*
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - spec/vcr_helper.rb
