global:
  scrape_interval: 60s

scrape_configs:
  - job_name: rails-react-monolith
    static_configs:
      - targets: ["web:3000"]

  - job_name: rails-react-monolith-sidekiq
    static_configs:
      - targets: ["sidekiq:9292"]
